### ISSUE TITLE
Instead of "Test Case-1 launched", just print the full / readable name of the test!

### ISSUE THREAD

**Issue by hokster7** [xareelee/XLTestLog#2]
Hi thanks for writing XLTestLog. It's made working with `XCTest` much more fun.

I think the test cases can be even clearer by removing numbering. Test numbers aren't useful anyway. Just use the full name of the test.

Would be good if it is made readable: e.g. `testThisWorks` => `"This works" passed`.

I think there's can be some lessons of simplicity and conciseness that can be learned from `mocha`, the Javascript test runner!

**Comment by xareelee** [comment]
Thanks for your suggestions.
1. Test case numbers are useful for me to know how many test cases have already been run. I prefer to keep them. Maybe the numbers could be combined with the test case names. 
2. Printing the readable full names is a good idea. I'd like to study `mocha` when I'm available, but not right now. Maybe you can make a pull request for the implementation. 
3. Keeping the original method names (and its class) is still important for me. I could find the test code easily when a test case fails.

**Comment by xareelee** [comment]
I've made the test logs more concise for readability without XcodeColors in **XLTestLog 1.2**. I'll close this issue.
